// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entites;

[Table("PROUDCTS")]
public partial class Proudct
{
    [Key]
    [Column("PRODUCT_ID")]
    public int ProductId { get; set; }

    [Column("PRODUCT_NAME")]
    [StringLength(50)]
    public string ProductName { get; set; }

    [Column("PRICE")]
    public int? Price { get; set; }

    [Column("CATEGORY_ID")]
    public int? CategoryId { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(50)]
    public string Description { get; set; }

    [Column("IMGPATH")]
    [StringLength(50)]
    public string Imgpath { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Proudcts")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}