// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entites;

[Table("User")]
public partial class User
{
    [Key]
    [Column("USER_ID")]
    public int UserId { get; set; }

    [Required]
    [Column("USER_NAME")]
    [StringLength(50)]
    public string UserName { get; set; }

    [Column("FIRST_NAME")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("LAST_NAME")]
    [StringLength(50)]
    public string LastName { get; set; }

    [Column("PASSWORD")]
    [StringLength(50)]
    public string Password { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}