// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Entites;

using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using static Microsoft.EntityFrameworkCore.DbContext;

namespace Repositories;

public partial class webApiDB8192Context : DbContext
{
    public webApiDB8192Context(DbContextOptions<webApiDB8192Context> options)
        : base(options)
    {
    }
    public webApiDB8192Context()
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Proudct> Proudcts { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasOne(d => d.User).WithMany(p => p.Orders).HasConstraintName("FK_USER_ID");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems).HasConstraintName("FK_ORDER_ID");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems).HasConstraintName("FK_PRODUCT_ID");
        });

        modelBuilder.Entity<Proudct>(entity =>
        {
            entity.HasOne(d => d.Category).WithMany(p => p.Proudcts).HasConstraintName("FK_CATEGORY_ID");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK_USERS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}